"""Initial migration

Revision ID: 37bdf75c8396
Revises: 1e7a9556c1b9
Create Date: 2025-03-25 11:37:35.599554

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '37bdf75c8396'
down_revision: Union[str, None] = '1e7a9556c1b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('category_table', 'created_at',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('category_table', 'modified_at',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('product_table', 'created_at',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('product_table', 'modified_at',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('subcategory_table', 'created_at',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('subcategory_table', 'modified_at',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('subcategory_table', 'modified_at',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('subcategory_table', 'created_at',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('product_table', 'modified_at',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('product_table', 'created_at',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('category_table', 'modified_at',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('category_table', 'created_at',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
