"""Initial migration

Revision ID: f557f927fbee
Revises: 37bdf75c8396
Create Date: 2025-03-25 11:45:04.972911

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'f557f927fbee'
down_revision: Union[str, None] = '37bdf75c8396'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('category_table', 'created_at',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=30),
               existing_nullable=True)
    op.alter_column('category_table', 'modified_at',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=30),
               existing_nullable=True)
    op.alter_column('product_table', 'created_at',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=30),
               existing_nullable=True)
    op.alter_column('product_table', 'modified_at',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=30),
               existing_nullable=True)
    op.alter_column('subcategory_table', 'created_at',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=30),
               existing_nullable=True)
    op.alter_column('subcategory_table', 'modified_at',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=30),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('subcategory_table', 'modified_at',
               existing_type=sa.String(length=30),
               type_=mysql.INTEGER(),
               existing_nullable=True)
    op.alter_column('subcategory_table', 'created_at',
               existing_type=sa.String(length=30),
               type_=mysql.INTEGER(),
               existing_nullable=True)
    op.alter_column('product_table', 'modified_at',
               existing_type=sa.String(length=30),
               type_=mysql.INTEGER(),
               existing_nullable=True)
    op.alter_column('product_table', 'created_at',
               existing_type=sa.String(length=30),
               type_=mysql.INTEGER(),
               existing_nullable=True)
    op.alter_column('category_table', 'modified_at',
               existing_type=sa.String(length=30),
               type_=mysql.INTEGER(),
               existing_nullable=True)
    op.alter_column('category_table', 'created_at',
               existing_type=sa.String(length=30),
               type_=mysql.INTEGER(),
               existing_nullable=True)
    # ### end Alembic commands ###
