"""Initial migration

Revision ID: e11e9f0fe781
Revises:
Create Date: 2025-03-19 23:39:00.354785

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "e11e9f0fe781"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "category_table",
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
    )
    op.add_column(
        "category_table",
        sa.Column(
            "modified_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.alter_column(
        "category_table",
        "is_deleted",
        existing_type=mysql.TINYINT(display_width=1),
        nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "category_table",
        "is_deleted",
        existing_type=mysql.TINYINT(display_width=1),
        nullable=False,
    )
    op.drop_column("category_table", "modified_at")
    op.drop_column("category_table", "created_at")
    # ### end Alembic commands ###
