"""Reverting category_id to id

Revision ID: f4f80ce76f8b
Revises: e11e9f0fe781
Create Date: 2025-03-20 23:46:23.810463

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "f4f80ce76f8b"
down_revision: Union[str, None] = "e11e9f0fe781"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_category_table_category_id", table_name="category_table")
    op.drop_index("ix_category_table_category_name", table_name="category_table")
    op.drop_table("category_table")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "category_table",
        sa.Column("id", mysql.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("category_name", mysql.VARCHAR(length=50), nullable=True),
        sa.Column("category_description", mysql.VARCHAR(length=100), nullable=True),
        sa.Column(
            "is_deleted",
            mysql.TINYINT(display_width=1),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "created_at",
            mysql.DATETIME(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "modified_at",
            mysql.DATETIME(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        mysql_collate="utf8mb4_0900_ai_ci",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    op.create_index(
        "ix_category_table_category_name",
        "category_table",
        ["category_name"],
        unique=True,
    )
    op.create_index(
        "ix_category_table_category_id", "category_table", ["id"], unique=False
    )
    # ### end Alembic commands ###
